apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: semics
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: appV3
  name: appV3
  namespace: semics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appV3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: appV3
    spec:
      containers:
      - image: acrsharedcommon93820.azurecr.io/appV3
        name: appV3
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: appV3
  name: appV3
  namespace: semics
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: appV3
  type: ClusterIP
status:
  loadBalancer: {}
